-- Create SEO table for centralized SEO management
CREATE TABLE IF NOT EXISTS seo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    page_route VARCHAR(255) NOT NULL UNIQUE,
    page_title VARCHAR(255) NOT NULL,
    meta_description TEXT,
    meta_keywords TEXT,
    og_title VARCHAR(255),
    og_description TEXT,
    og_image VARCHAR(500),
    twitter_title VARCHAR(255),
    twitter_description TEXT,
    twitter_image VARCHAR(500),
    canonical_url VARCHAR(500),
    robots VARCHAR(100) DEFAULT 'index, follow',
    author VARCHAR(100),
    language VARCHAR(10) DEFAULT 'en',
    geo_region VARCHAR(50),
    geo_placename VARCHAR(100),
    geo_position VARCHAR(50),
    schema_type VARCHAR(50),
    schema_data JSON,
    priority DECIMAL(2,1) DEFAULT 0.5,
    change_frequency VARCHAR(20) DEFAULT 'monthly',
    is_active BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert default SEO data for existing pages
INSERT INTO seo (page_route, page_title, meta_description, meta_keywords, og_title, og_description, og_image, canonical_url, robots, author, language, geo_region, geo_placename, geo_position, schema_type, priority, change_frequency) VALUES

-- Homepage
('/', 'Road to SDET - Empowering Software Testers', 
'Road to SDET offers industry-ready SQA training, full stack testing courses, expert mentorship, and hands-on projects.', 
'SQA Training, SQA Online Course, SQA Course Bangladesh, SQA Course in Bangladesh, SQA Course Dhaka, SQA Course BD, SQA Course Online, SQA Course for Beginners, Best SQA course in Bangladesh, Full Stack SDET, Software Testing, QA Courses, Playwright Training Bangladesh, Selenium Training BD, Postman Training Bangladesh, Rest Assured Training, Manual Testing Course, Automation Testing Training, CI/CD Training Bangladesh, Test Automation BD, Quality Assurance Course, QA Certification Bangladesh, SDET Bangladesh, Road to SDET, Roadtocareer.net',
'Road to SDET - Empowering Software Testers',
'Join the best SQA and full stack SDET hands-on courses in Bangladesh. Learn automation, manual testing, CI/CD, and more.',
'https://roadtocareer.net/og-image.jpg',
'https://roadtocareer.net',
'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
'Road to SDET',
'en',
'BD',
'Dhaka',
'23.8103, 90.4125',
'Organization',
1.0,
'daily'),

-- QA Talent Page
('/qa-talent', 'Find Talented SQA - Road to Career | QA & SDET Professionals Bangladesh',
'Discover talented QA and SDET professionals from Bangladesh. Browse skilled software testers, automation engineers, and quality assurance specialists trained at Road to SDET.',
'hire QA engineers Bangladesh, SDET professionals Dhaka, software testing talent, quality assurance experts, automation testers Bangladesh, find QA talent, hire software testers, selenium experts, automation testing professionals, manual testers Bangladesh, ISTQB certified professionals',
'Find Talented SQA | Road to Career - QA & SDET Professionals',
'Discover talented QA and SDET professionals from Bangladesh. Skilled in automation testing, API testing, manual testing, and more.',
'https://roadtocareer.net/logo.png',
'https://roadtocareer.net/qa-talent',
'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
'Road to Career',
'en',
'BD',
'Dhaka',
'23.8103, 90.4125',
'CollectionPage',
0.9,
'daily'),

-- Jobs Page
('/jobs', 'QA & SDET Jobs in Bangladesh | Road to SDET',
'Find the latest QA and SDET job opportunities in Bangladesh. Quality Assurance, Test Automation, Manual Testing, and Software Testing positions.',
'QA jobs Bangladesh, SDET jobs Dhaka, software testing jobs, quality assurance careers, automation testing jobs Bangladesh, manual testing jobs, QA engineer jobs, test automation careers, software QA jobs Dhaka',
'QA & SDET Jobs in Bangladesh | Road to SDET',
'Find the latest QA and SDET job opportunities in Bangladesh. Quality Assurance, Test Automation, and Software Testing positions.',
'https://roadtocareer.net/logo.png',
'https://roadtocareer.net/jobs',
'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
'Road to SDET',
'en',
'BD',
'Dhaka',
'23.8103, 90.4125',
'JobPosting',
0.9,
'daily'),

-- Reviews Page
('/reviews', 'Student Reviews & Success Stories - Road to SDET Bangladesh | Testimonials',
'Read real student reviews about Road to SDET\'s QA and SDET courses in Bangladesh. Verified success stories from students placed at top companies.',
'Road to SDET reviews, student testimonials Bangladesh, QA course reviews, SDET training feedback, software testing course Bangladesh, student success stories, QA engineer testimonials, automation testing reviews Dhaka',
'Student Reviews & Success Stories | Road to SDET Bangladesh',
'Verified reviews from real students. Learn why Road to SDET is Bangladesh\'s top choice for QA and automation testing training.',
'https://roadtocareer.net/logo.png',
'https://roadtocareer.net/reviews',
'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
'Road to SDET',
'en',
'BD',
'Dhaka',
'23.8103, 90.4125',
'EducationalOrganization',
0.9,
'weekly'),

-- Login Page
('/login', 'Login | Road to SDET',
'Login to your Road to SDET student or admin dashboard to manage your courses, attendance, payments and more.',
'Road to SDET login, student login, admin login, dashboard access',
'Login | Road to SDET',
'Login to your Road to SDET student dashboard',
'https://roadtocareer.net/logo.png',
'https://roadtocareer.net/login',
'noindex, nofollow',
'Road to SDET',
'en',
'BD',
'Dhaka',
'23.8103, 90.4125',
'WebPage',
0.3,
'monthly');
