CREATE TABLE event_forms (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  short_description TEXT NOT NULL,
  event_date DATETIME NOT NULL,
  fields_json JSON NOT NULL,
  created_by INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE audience (
  id INT PRIMARY KEY AUTO_INCREMENT,
  event_form_id INT NOT NULL,
  submitted_data JSON NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (event_form_id) REFERENCES event_forms(id) ON DELETE CASCADE
);
